//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskStatus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depatment
    {
        public decimal Dept_Id { get; set; }
        public string Depatment1 { get; set; }
    }
}
